FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN apt-get update && apt-get install -y netcat-openbsd

COPY . .

RUN npx prisma generate
RUN #npx prisma migrate dev --name init

# tsoaのルート生成
RUN npm run tsoa:gen

COPY entrypoint.dev.sh .
RUN chmod +x entrypoint.dev.sh

EXPOSE 3001

CMD ["./entrypoint.dev.sh"]
