FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npx prisma migrate dev --name init

# tsoaのルート生成
RUN npm run tsoa:gen

EXPOSE 3001

CMD ["npm", "run", "dev"]
